name: Build and deploy Drupal 9 app to Azure Web App - andiekobbietechie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Install composer dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Copy Drupal files
        if: steps.check_files.outputs.files_exists == 'true'
        run: cp -R . /var/www/html

      - name: Create settings.php file
        if: steps.check_files.outputs.files_exists == 'true'
        run: cp /var/www/html/sites/default/default.settings.php /var/www/html/sites/default/settings.php && chmod 777 /var/www/html/sites/default/settings.php

      - name: Set database connection string
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "\$databases['default']['default'] = array (" >> /var/www/html/sites/default/settings.php
          echo "  'database' => \${{ secrets.andiekobbietechie }}," >> /var/www/html/sites/default/settings.php
          echo "  'username' => \${{ secrets.andiekobbie }}," >> /var/www/html/sites/default/settings.php
          echo "  'password' => \${{ secrets.Bio.tecno.97 }}," >> /var/www/html/sites/default/settings.php
          echo "  'prefix' => ''," >> /var/www/html/sites/default/settings.php
          echo "  'host' => \${{ secrets.drupalamp.mysql.database.azure.com }}," >> /var/www/html/sites/default/settings.php
          echo "  'port' => \${{ secrets.3306 }}," >> /var/www/html/sites/default/settings.php
          echo "  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql'," >> /var/www/html/sites/default/settings.php
          echo "  'driver' => 'mysql'," >> /var/www/html/sites/default/settings.php
          echo ");" >> /var/www/html/sites/default/settings.php

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: drupal-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: drupal-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'andiekobbietechie'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_88CF46FE824F4A3F8C4F37A5FDAD0E03 }}
          package: .
