name: Build and deploy Drupal 9 app to Azure Web App - andiekobbietechie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Install composer dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Copy Drupal files
        if: steps.check_files.outputs.files_exists == 'true'
        run: cp -R . /var/www/html

      - name: Create settings.php file
        if: steps.check_files.outputs.files_exists == 'true'
        run: cp /var/www/html/sites/default/default.settings.php /var/www/html/sites/default/settings.php && chmod 777 /var/www/html/sites/default/settings.php

      - name: Set database connection string
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "\$databases['default']['default'] = array (" >> /var/www/html/sites/default/settings.php
          echo "  'database' => \${{ secrets.andiekobbietechie }}," >> /var/www/html/sites/default/settings.php
          echo "  'username' => \${{ secrets.andiekobbie }}," >> /var/www/html/sites/default/settings.php
          echo "  'password' => \${{ secrets.Biotecno97 }}," >> /var/www/html/sites/default/settings.php
          echo "  'prefix' => ''," >> /var/www/html/sites/default/settings.php
          echo "  'host' => \${{ secrets.drupalamp.mysql.database.azure.com }}," >> /var/www/html/sites/default/settings.php
          echo "  'port' => '3306'," >> /var/www/html/sites/default/settings.php
          echo "  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql'," >> /var/www/html/sites/default/settings.php
          echo "  'driver' => 'mysql'," >> /var/www/html/sites/default/settings.php
          echo ");" >> /var/www/html/sites/default/settings.php

      - name: Run Drupal 9 install wizard
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cd /var/www/html
          vendor/bin/drush site-install --db-url=mysql://{{ secrets.andiekobbie }}:{{ secrets.Biotecno97 }}@{{ secrets.drupalamp.mysql.database.azure.com }}/drupalamp -y

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: drupal-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: drupal-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'andiekobbietechie'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D295D96B2AAB4654A7EFEE8702CDD97A }}
          package: .
          
      - name: Run Drupal 9 Install Wizard
        uses: Azure/install-drupal@v1
        with:
          app-name: 'andiekobbietechie'
          slot-name: 'Production'
          drupal-version: '9.5.5'
          database-provider: 'mysql'
          database-type: 'mysql'
          database-name: ${{ secrets.andiekobbietechie }}
          database-user-name: ${{ secrets.andiekobbie }}
          database-user-password: ${{ secrets.Biotecno97 }}
          db-server: ${{ secrets.drupalamp.mysql.database.azure.com }}
          db-port: '3306'
          site-name: 'My Drupal 9 Site'
          site-admin-name: 'andiekobbie'
          site-admin-password: ${{ secrets.Biotecno97 }}
          site-admin-email: 'andre.enne@yahoo.com'
